### ISSUE TITLE
SdlManagerListener.onDestroy not called after BT disconnect

### ISSUE THREAD

**Issue by ashwink11** [smartdevicelink/sdl_android#932]
### Bug Report 
Hello SDL Android App kept showing notification even after Bluetooth connection disconnect. SdlManagerListener.onDestroy not called and hence service was not stopped.

##### Reproduction Steps
1. Connect App using BT to Ford SYNC
2. Go to SYNC settings and switch off BT
3. App keep showing connected through SDL notification

##### Expected Behavior
SdlManagerListener onDestroy should be called after BT disconnect with SYNC.

##### Observed Behavior
SdlManagerListener onDestroy not called after BT disconnect with SYNC.

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.7.2
* Testing Against: Ford SYNC

##### Test Case, Sample Code, and / or Example App
Hello SDL Android App from github
![notification_issue](https://user-images.githubusercontent.com/24958343/49078593-bdbd6400-f23e-11e8-83c2-0f4f622e01f9.png)

**Comment by joeygrover** [comment]
I am unable to reproduce this issue as described. Please share more details on setup and reproduction steps otherwise I will close the issue.

**Comment by ashwink11** [comment]
I see this issue everytime, I connect Android device using BT. Other SDL apps installed on device are with SDL library 4.6.0 and 4.6.2. Device used is Pixel. I shared logs in Slack.

**Comment by joeygrover** [comment]
If it happens every time for you then there is something specific with your setup that is causing it. Without all that information it is very difficult to pin point the problem. What build flavor were you using of the Hello Sdl app? What other apps were installed on the phone? Have you tried removing those apps and only running Hello Sdl to see if the problem persisted? 

Attaching logs that were sent
[issue_932.log](https://github.com/smartdevicelink/sdl_android/files/2624941/issue_932.log)

**Comment by ashwink11** [comment]
What build flavor were you using of the Hello Sdl app?
multi_sec_lowDebug
What other apps were installed on the phone?
Apps in development stage, using SDL library 4.6.0 and 4.6.2
Have you tried removing those apps and only running Hello Sdl to see if the problem persisted?
Problem seen every time, when App with SDL library 4.6.0 is installed on device.

**Comment by khburdette** [comment]
We are also seeing this issue with the multiplexing transport as well. The best example that's 100% reproducible is Ford+Alexa and Webex installed on the device at the same time. Ford+Alexa is using 4.5 and Webex using 4.7. The older router service isn't reporting the MAC address, so the newer router service doesn't think it's the primary transport and therefore doesn't call dispose. See attached screenshot of Webex foreground service running after disconnecting from head unit.

We are getting reports that new apps are also seeing issues with older library versions and they are "patching" their libraries, so this definitely needs to be investigated and fixed.

![Screenshot_20190321-124932](https://user-images.githubusercontent.com/1591471/54918939-dfb9b100-4ed5-11e9-9694-f695dabee925.png)

**Comment by joeygrover** [comment]
This has been fixed and will be part of the next release

**Comment by Tnnnguyen** [comment]
This issue is still there.  The flow is:
1. Delete all SDL enabled apps from device
2. Install Ford Alexa app, connect to tdk, Alexa shows and hosts router service
3. Install Hello Sdl app, app also shows on tdk
4. Turn off tdk, for Hello Sdl app: SdlManagerListener's onDestroy() does not get called, app does not get a chance to clean up.

Sdl Android Library: 4.8 RC
Device: Pixel XL
Device OS: Android 9
Tdk: MY18, SYNC3v2

**Comment by joeygrover** [comment]
Investigating.

**Comment by Tnnnguyen** [comment]
The bug is the result of this [if](https://github.com/smartdevicelink/sdl_android/blob/efc9fdc641a55afb7d8331d5cab709f602feebea/sdl_android/src/main/java/com/smartdevicelink/protocol/SdlProtocol.java#L1153) statement failure.  It is moved to `SdlProtocolBase.java` in 4.8 RC and more comparison added to the statement but still fails.

The reason is that `disconnectedTransport` has a null address whereas `getTransportForSession(SessionType.RPC)` returns a TransportRecord object with the address of the empty String.  So the comparison code fails the statement.

Tracing back all the way to `TransportBroker.java`, at this [line](https://github.com/smartdevicelink/sdl_android/blob/490be41b20ec4bb4a81837e73eb6ea9bfcea7a8a/sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java#L332), the newly TransportRecord should have an empty String instead of the null address:
`
broker.onHardwareDisconnected(new TransportRecord(transportType, ""), null);
`
instead of:
`
broker.onHardwareDisconnected(new TransportRecord(transportType, null), null);
`

This would make the if statement above true during hardware disconnect and clean up code invoked.

**Comment by joeygrover** [comment]
Yea it seems there's a mismatch between empty string and null. I think making a constant transport record for this case makes sense to prevent any mismatch again. Alternatively the overridden equals could say empty string and null are equal addresses.

**Comment by Tnnnguyen** [comment]
My vote against 
> Alternatively the overridden equals could say empty string and null are equal addresses.

although it should work.

**Comment by joeygrover** [comment]
Same, that is why I put it as `Alternatively`. ;)

**Comment by joeygrover** [comment]
Also [this line](https://github.com/smartdevicelink/sdl_android/blob/490be41b20ec4bb4a81837e73eb6ea9bfcea7a8a/sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java#L367) could be trouble. Since the SdlProtocol is going to assign that connected transport with a potential address I would say it's best to remove that line and stick with the logic of old router services will simply have the TransportRecord of Type: Bluetooth,  Address: null for simplicity.

**Comment by joeygrover** [comment]
PR ready for review #1021

**Comment by joeygrover** [comment]
Thanks to @Tnnnguyen the issue has been root caused, and actually fixed with #1021. RC2_4.8.0 will be pushed ASAP.

**Comment by ashwink11** [comment]
Issue still visible in RC2-4.8.0 release. 

Phone used: Pixel 2 Android 9

Apps installed:
1. Ford Pass
2. nTV
3. WebEx
4. Hello SDL
5. Ford App Catalogue
[sdl_issue.txt](https://github.com/smartdevicelink/sdl_android/files/3034438/sdl_issue.txt)

**Comment by joeygrover** [comment]
Which library versions do each of those apps have? And which apps still displayed the issue?

**Comment by Tnnnguyen** [comment]
@ashwink11 can we please get a more detailed steps to reproduce and observations?
For example:
- Are all apps discovered the first time?
- Which app is hosting the router service? Screenshot of the pulled down notification.
- After BT/ignition cycled, which app is not discovered? Which app is hosting now? Screenshot of the pulled down notification.

**Comment by Tnnnguyen** [comment]
@ashwink11 what app is nTV? Can we get access to it?

**Comment by ashwink11** [comment]
Tested again with less number of Apps.
1. WebEx - Downloaded from Play Store
2. ACast - Downloaded from Play Store.
3. Hello SDL Android - Built from tag RC2-4.8.0 APK attached.

From the logs, I see SDL Lib versions as follows:
ACast -  SDL_LIB_VERSION: 4.5.0
WebEx - SDL_LIB_VERSION: 4.7.1
Hello SDL -  SDL_LIB_VERSION: RC2-4.8.0
[sdl_issue.txt](https://github.com/smartdevicelink/sdl_android/files/3038679/sdl_issue.txt)
[hello_sdl_android-multi_sec_off-debug.apk.zip](https://github.com/smartdevicelink/sdl_android/files/3038680/hello_sdl_android-multi_sec_off-debug.apk.zip)

**Comment by joeygrover** [comment]
Can you please answer the other questions as it is not possible to investigate with only the information provided.

**Comment by joeygrover** [comment]
@ashwink11 since the hello SDL app is the only app that would receive the fix, can you ensure it has the debug tool enabled, then grep log cat for only it's logs?

**Comment by bilal-alsharifi** [comment]
We did different combinations of tests on multiple apps and found that the issue only happens when an app with an old version of sdl_android connects in legacy mode. We were not able to reproduce the issue with 4.8 apps. So it looks like the issue is fixed in 4.8. The tests that we did and their resutls are summarized [here](https://docs.google.com/spreadsheets/d/1qu4bCdInqHuhHjR7z5lQYTcwiQXjFez0V7vcNHPABus/edit?usp=sharing)

**Comment by ashwink11** [comment]
> Which library versions do each of those apps have? And which apps still displayed the issue? 

Hello SDL App built from tag RC2-4.8.0 and WebEx app has notification issue. Library versions mentioned in previous comment.

> @ashwink11 can we please get a more detailed steps to reproduce and observations?

1. Install WebEx and Acast App from Play Store
2. Install Hello SDL App from Tag RC2 or [use attached APK. ](https://github.com/smartdevicelink/sdl_android/files/3038680/hello_sdl_android-multi_sec_off-debug.apk.zip)
3. Connect Android device to SYNC
4. Wait for all Apps to show up on SYNC. Observe notifications on Android device. All 3 apps will show notifications.
5. Disable Bluetooth on Ford SYNC. Alternatively, perform Ignition Cycle
6. WebEx and Hello SDL App continues to show notification after disconnection. ACast does not show notification.

Please refer screenshot below for re-connection behavior.

> * Are all apps discovered the first time?

Yes

> * Which app is hosting the router service? Screenshot of the pulled down notification.

Looks like Hello SDL App hosted router service

![sdl_android_issue_1](https://user-images.githubusercontent.com/24958343/55536508-3daa7d80-56ba-11e9-8add-be4b7f89343d.png)


> * After BT/ignition cycled, which app is not discovered? Which app is hosting now? Screenshot of the pulled down notification.

**Only Acast was detected after BT disconnect/ connect. WebEx and Hello SDL App continues to show notification on Phone, but was not registered on Ford SYNC.**

After disconnect Screen shot. (Disable Bluetooth on SYNC)

![sdl_android_issue_2](https://user-images.githubusercontent.com/24958343/55536805-fffa2480-56ba-11e9-86d0-b691a2eaeb12.png)


Reconnecting Again  (Enable Bluetooth on SYNC)

![sdl_android_issue_3](https://user-images.githubusercontent.com/24958343/55536810-038dab80-56bb-11e9-9bd6-cdf0aff7a4b9.png)

**Comment by ashwink11** [comment]
> We did different combinations of tests on multiple apps and found that the issue only happens when an app with an old version of sdl_android connects in legacy mode. We were not able to reproduce the issue with 4.8 apps. The tests that we did and their results are summarized [here](https://docs.google.com/spreadsheets/d/1qu4bCdInqHuhHjR7z5lQYTcwiQXjFez0V7vcNHPABus/edit?usp=sharing)

In this test only "app2 notifcation stays", which is expected as App2 used in test always use lib version 4.7.X
Please use apps with older version of library as well, with this combination, issue can be seen with 4.8 apps as well.

**Comment by joeygrover** [comment]
@ashwink11 Thank you for the detailed response. We will follow your steps exactly and see if we can reproduce. Were you able to get logs from the hello sdl app with the DebugTool enabled?

**Comment by joeygrover** [comment]
@ashwink11 please give the RC branch a new test with the merged changes from #1030. The previous fix actually exposed a different issue that resulted in the same miss from the onDestroy.

**Comment by ashwink11** [comment]
I did some tests with RC3 and do not see this issue. 

Could you please let us know how to enable DebugTool for Hello SDL?

**Comment by BrettyWhite** [comment]
Before you start your `SdlManager` call `DebugTool.enableDebugTool();`

**Comment by joeygrover** [comment]
That's great news!

The DebugTool is in the library itself so any app can use it. We've started to move our library logs there because apps were getting too chatty in LogCat.

**Comment by theresalech** [comment]
Closed via #1030
